name: push-develop
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          cat $HOME/files_removed.json
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
          echo '${{ steps.file_changes.outputs.files_removed}}'
      - run: |
         echo ${{ steps.file_changes.outputs.files}} > world.txt
      - uses: actions/upload-artifact@v1
        with:
          name: files
          path: world.txt
          
  loopcheck:
    needs: changes
    runs-on: [ubuntu-latest]
    steps:
      - name: download
        uses: actions/download-artifact@v1
        with:
          name: files
      - name: echo
        run: cat files/world.txt
