name: push-develop
on:
  pull_request:
    branches: master
  push:
    branches: master
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          cat $HOME/files_removed.json
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
          echo '${{ steps.file_changes.outputs.files_removed}}'
      - run: echo ${{ steps.file_changes.outputs.files}} > files.txt
      - name: uploading artifact
      - uses: actions/upload-artifact@v1
        with:
          name: files
          path: files.txt

  loopcheck:
    runs-on: [ubuntu-latest]
    steps:
        - uses: actions/checkout@v2
        - uses: actions/download-artifact@v1
          with:
           name: files
        - run: cat files/files.txt
                
